spring:
  application:
    name: TaskManagementSystem
# H2 Database

  datasource:
            url: jdbc:h2:file:./data/testdb
            driver-class-name: org.h2.Driver
            username: sa
            password: Lap123456


  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true

#Enable H2 Console
  h2:
      console:
          enabled: true
          path: /h2-console

#security

security:
  user:
    name: admin
    password: 123456
    roles: USER